name: Sync to Hugging Face Spaces
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - run: echo ${{ github.repository.owner }}
      - run: echo ${{ github.repository_owner }}
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://${{ github.repository.owner }}:$HF_TOKEN@huggingface.co/spaces/${{ github.repository }} main